require 'mongoid'
require 'haml'
require 'sinatra/base'

require "fnordmetric/core"
require "fnordmetric/app"
require "fnordmetric/metric_api"
require "fnordmetric/dispatch"
require "fnordmetric/dashboard"
require "fnordmetric/event"
require "fnordmetric/cache"
require "fnordmetric/report"
require "fnordmetric/metric"
require "fnordmetric/average_metric"
require "fnordmetric/count_metric"
require "fnordmetric/combine_metric"
require "fnordmetric/sum_metric"
require "fnordmetric/widget"
require "fnordmetric/numbers_widget"
require "fnordmetric/timeline_widget"
require "fnordmetric/funnel_widget"