#!/bin/bash

sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Analyzer.h"/#include "fnord-fts\/analysis\/Analyzer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ASCIIFoldingFilter.h"/#include "fnord-fts\/analysis\/ASCIIFoldingFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BaseCharFilter.h"/#include "fnord-fts\/analysis\/BaseCharFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CachingTokenFilter.h"/#include "fnord-fts\/analysis\/CachingTokenFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CharArraySet.h"/#include "fnord-fts\/analysis\/CharArraySet.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CharFilter.h"/#include "fnord-fts\/analysis\/CharFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CharReader.h"/#include "fnord-fts\/analysis\/CharReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CharStream.h"/#include "fnord-fts\/analysis\/CharStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CharTokenizer.h"/#include "fnord-fts\/analysis\/CharTokenizer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ISOLatin1AccentFilter.h"/#include "fnord-fts\/analysis\/ISOLatin1AccentFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}KeywordAnalyzer.h"/#include "fnord-fts\/analysis\/KeywordAnalyzer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}KeywordTokenizer.h"/#include "fnord-fts\/analysis\/KeywordTokenizer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LengthFilter.h"/#include "fnord-fts\/analysis\/LengthFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LetterTokenizer.h"/#include "fnord-fts\/analysis\/LetterTokenizer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LowerCaseFilter.h"/#include "fnord-fts\/analysis\/LowerCaseFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LowerCaseTokenizer.h"/#include "fnord-fts\/analysis\/LowerCaseTokenizer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MappingCharFilter.h"/#include "fnord-fts\/analysis\/MappingCharFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NormalizeCharMap.h"/#include "fnord-fts\/analysis\/NormalizeCharMap.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NumericTokenStream.h"/#include "fnord-fts\/analysis\/NumericTokenStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PerFieldAnalyzerWrapper.h"/#include "fnord-fts\/analysis\/PerFieldAnalyzerWrapper.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PorterStemFilter.h"/#include "fnord-fts\/analysis\/PorterStemFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PorterStemmer.h"/#include "fnord-fts\/analysis\/PorterStemmer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SimpleAnalyzer.h"/#include "fnord-fts\/analysis\/SimpleAnalyzer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StandardAnalyzer.h"/#include "fnord-fts\/analysis\/standard\/StandardAnalyzer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StandardFilter.h"/#include "fnord-fts\/analysis\/standard\/StandardFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StandardTokenizer.h"/#include "fnord-fts\/analysis\/standard\/StandardTokenizer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StandardTokenizerImpl.h"/#include "fnord-fts\/analysis\/standard\/StandardTokenizerImpl.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StopAnalyzer.h"/#include "fnord-fts\/analysis\/StopAnalyzer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StopFilter.h"/#include "fnord-fts\/analysis\/StopFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TeeSinkTokenFilter.h"/#include "fnord-fts\/analysis\/TeeSinkTokenFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Token.h"/#include "fnord-fts\/analysis\/Token.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FlagsAttribute.h"/#include "fnord-fts\/analysis\/tokenattributes\/FlagsAttribute.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}OffsetAttribute.h"/#include "fnord-fts\/analysis\/tokenattributes\/OffsetAttribute.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PayloadAttribute.h"/#include "fnord-fts\/analysis\/tokenattributes\/PayloadAttribute.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PositionIncrementAttribute.h"/#include "fnord-fts\/analysis\/tokenattributes\/PositionIncrementAttribute.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermAttribute.h"/#include "fnord-fts\/analysis\/tokenattributes\/TermAttribute.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TypeAttribute.h"/#include "fnord-fts\/analysis\/tokenattributes\/TypeAttribute.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TokenFilter.h"/#include "fnord-fts\/analysis\/TokenFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Tokenizer.h"/#include "fnord-fts\/analysis\/Tokenizer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TokenStream.h"/#include "fnord-fts\/analysis\/TokenStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}WhitespaceAnalyzer.h"/#include "fnord-fts\/analysis\/WhitespaceAnalyzer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}WhitespaceTokenizer.h"/#include "fnord-fts\/analysis\/WhitespaceTokenizer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}WordlistLoader.h"/#include "fnord-fts\/analysis\/WordlistLoader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}AbstractField.h"/#include "fnord-fts\/document\/AbstractField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CompressionTools.h"/#include "fnord-fts\/document\/CompressionTools.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DateField.h"/#include "fnord-fts\/document\/DateField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DateTools.h"/#include "fnord-fts\/document\/DateTools.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Document.h"/#include "fnord-fts\/document\/Document.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Field.h"/#include "fnord-fts\/document\/Field.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Fieldable.h"/#include "fnord-fts\/document\/Fieldable.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldSelector.h"/#include "fnord-fts\/document\/FieldSelector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LoadFirstFieldSelector.h"/#include "fnord-fts\/document\/LoadFirstFieldSelector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MapFieldSelector.h"/#include "fnord-fts\/document\/MapFieldSelector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NumberTools.h"/#include "fnord-fts\/document\/NumberTools.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NumericField.h"/#include "fnord-fts\/document\/NumericField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SetBasedFieldSelector.h"/#include "fnord-fts\/document\/SetBasedFieldSelector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}AbstractAllTermDocs.h"/#include "fnord-fts\/index\/AbstractAllTermDocs.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}AllTermDocs.h"/#include "fnord-fts\/index\/AllTermDocs.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BufferedDeletes.h"/#include "fnord-fts\/index\/BufferedDeletes.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ByteBlockPool.h"/#include "fnord-fts\/index\/ByteBlockPool.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ByteSliceReader.h"/#include "fnord-fts\/index\/ByteSliceReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ByteSliceWriter.h"/#include "fnord-fts\/index\/ByteSliceWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CharBlockPool.h"/#include "fnord-fts\/index\/CharBlockPool.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CheckIndex.h"/#include "fnord-fts\/index\/CheckIndex.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CompoundFileReader.h"/#include "fnord-fts\/index\/CompoundFileReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CompoundFileWriter.h"/#include "fnord-fts\/index\/CompoundFileWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ConcurrentMergeScheduler.h"/#include "fnord-fts\/index\/ConcurrentMergeScheduler.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DefaultSkipListReader.h"/#include "fnord-fts\/index\/DefaultSkipListReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DefaultSkipListWriter.h"/#include "fnord-fts\/index\/DefaultSkipListWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DirectoryReader.h"/#include "fnord-fts\/index\/DirectoryReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocConsumer.h"/#include "fnord-fts\/index\/DocConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocConsumerPerThread.h"/#include "fnord-fts\/index\/DocConsumerPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldConsumer.h"/#include "fnord-fts\/index\/DocFieldConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldConsumerPerField.h"/#include "fnord-fts\/index\/DocFieldConsumerPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldConsumerPerThread.h"/#include "fnord-fts\/index\/DocFieldConsumerPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldConsumers.h"/#include "fnord-fts\/index\/DocFieldConsumers.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldConsumersPerField.h"/#include "fnord-fts\/index\/DocFieldConsumersPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldConsumersPerThread.h"/#include "fnord-fts\/index\/DocFieldConsumersPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldProcessor.h"/#include "fnord-fts\/index\/DocFieldProcessor.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldProcessorPerField.h"/#include "fnord-fts\/index\/DocFieldProcessorPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocFieldProcessorPerThread.h"/#include "fnord-fts\/index\/DocFieldProcessorPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocInverter.h"/#include "fnord-fts\/index\/DocInverter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocInverterPerField.h"/#include "fnord-fts\/index\/DocInverterPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocInverterPerThread.h"/#include "fnord-fts\/index\/DocInverterPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocumentsWriter.h"/#include "fnord-fts\/index\/DocumentsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocumentsWriterThreadState.h"/#include "fnord-fts\/index\/DocumentsWriterThreadState.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldInfo.h"/#include "fnord-fts\/index\/FieldInfo.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldInfos.h"/#include "fnord-fts\/index\/FieldInfos.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldInvertState.h"/#include "fnord-fts\/index\/FieldInvertState.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldSortedTermVectorMapper.h"/#include "fnord-fts\/index\/FieldSortedTermVectorMapper.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldsReader.h"/#include "fnord-fts\/index\/FieldsReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldsWriter.h"/#include "fnord-fts\/index\/FieldsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FilterIndexReader.h"/#include "fnord-fts\/index\/FilterIndexReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsDocsConsumer.h"/#include "fnord-fts\/index\/FormatPostingsDocsConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsDocsWriter.h"/#include "fnord-fts\/index\/FormatPostingsDocsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsFieldsConsumer.h"/#include "fnord-fts\/index\/FormatPostingsFieldsConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsFieldsWriter.h"/#include "fnord-fts\/index\/FormatPostingsFieldsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsPositionsConsumer.h"/#include "fnord-fts\/index\/FormatPostingsPositionsConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsPositionsWriter.h"/#include "fnord-fts\/index\/FormatPostingsPositionsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsTermsConsumer.h"/#include "fnord-fts\/index\/FormatPostingsTermsConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FormatPostingsTermsWriter.h"/#include "fnord-fts\/index\/FormatPostingsTermsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FreqProxFieldMergeState.h"/#include "fnord-fts\/index\/FreqProxFieldMergeState.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FreqProxTermsWriter.h"/#include "fnord-fts\/index\/FreqProxTermsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FreqProxTermsWriterPerField.h"/#include "fnord-fts\/index\/FreqProxTermsWriterPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FreqProxTermsWriterPerThread.h"/#include "fnord-fts\/index\/FreqProxTermsWriterPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexCommit.h"/#include "fnord-fts\/index\/IndexCommit.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexDeletionPolicy.h"/#include "fnord-fts\/index\/IndexDeletionPolicy.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexFileDeleter.h"/#include "fnord-fts\/index\/IndexFileDeleter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexFileNameFilter.h"/#include "fnord-fts\/index\/IndexFileNameFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexFileNames.h"/#include "fnord-fts\/index\/IndexFileNames.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexReader.h"/#include "fnord-fts\/index\/IndexReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexWriter.h"/#include "fnord-fts\/index\/IndexWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IntBlockPool.h"/#include "fnord-fts\/index\/IntBlockPool.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InvertedDocConsumer.h"/#include "fnord-fts\/index\/InvertedDocConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InvertedDocConsumerPerField.h"/#include "fnord-fts\/index\/InvertedDocConsumerPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InvertedDocConsumerPerThread.h"/#include "fnord-fts\/index\/InvertedDocConsumerPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InvertedDocEndConsumer.h"/#include "fnord-fts\/index\/InvertedDocEndConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InvertedDocEndConsumerPerField.h"/#include "fnord-fts\/index\/InvertedDocEndConsumerPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InvertedDocEndConsumerPerThread.h"/#include "fnord-fts\/index\/InvertedDocEndConsumerPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}KeepOnlyLastCommitDeletionPolicy.h"/#include "fnord-fts\/index\/KeepOnlyLastCommitDeletionPolicy.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LogByteSizeMergePolicy.h"/#include "fnord-fts\/index\/LogByteSizeMergePolicy.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LogDocMergePolicy.h"/#include "fnord-fts\/index\/LogDocMergePolicy.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LogMergePolicy.h"/#include "fnord-fts\/index\/LogMergePolicy.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MergeDocIDRemapper.h"/#include "fnord-fts\/index\/MergeDocIDRemapper.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MergePolicy.h"/#include "fnord-fts\/index\/MergePolicy.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MergeScheduler.h"/#include "fnord-fts\/index\/MergeScheduler.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiLevelSkipListReader.h"/#include "fnord-fts\/index\/MultiLevelSkipListReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiLevelSkipListWriter.h"/#include "fnord-fts\/index\/MultiLevelSkipListWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultipleTermPositions.h"/#include "fnord-fts\/index\/MultipleTermPositions.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiReader.h"/#include "fnord-fts\/index\/MultiReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NormsWriter.h"/#include "fnord-fts\/index\/NormsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NormsWriterPerField.h"/#include "fnord-fts\/index\/NormsWriterPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NormsWriterPerThread.h"/#include "fnord-fts\/index\/NormsWriterPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ParallelReader.h"/#include "fnord-fts\/index\/ParallelReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Payload.h"/#include "fnord-fts\/index\/Payload.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PositionBasedTermVectorMapper.h"/#include "fnord-fts\/index\/PositionBasedTermVectorMapper.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}RawPostingList.h"/#include "fnord-fts\/index\/RawPostingList.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ReadOnlyDirectoryReader.h"/#include "fnord-fts\/index\/ReadOnlyDirectoryReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ReadOnlySegmentReader.h"/#include "fnord-fts\/index\/ReadOnlySegmentReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ReusableStringReader.h"/#include "fnord-fts\/index\/ReusableStringReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentInfo.h"/#include "fnord-fts\/index\/SegmentInfo.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentInfoCollection.h"/#include "fnord-fts\/index\/SegmentInfoCollection.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentInfos.h"/#include "fnord-fts\/index\/SegmentInfos.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentMergeInfo.h"/#include "fnord-fts\/index\/SegmentMergeInfo.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentMergeQueue.h"/#include "fnord-fts\/index\/SegmentMergeQueue.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentMerger.h"/#include "fnord-fts\/index\/SegmentMerger.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentReader.h"/#include "fnord-fts\/index\/SegmentReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentTermDocs.h"/#include "fnord-fts\/index\/SegmentTermDocs.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentTermEnum.h"/#include "fnord-fts\/index\/SegmentTermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentTermPositions.h"/#include "fnord-fts\/index\/SegmentTermPositions.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentTermPositionVector.h"/#include "fnord-fts\/index\/SegmentTermPositionVector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentTermVector.h"/#include "fnord-fts\/index\/SegmentTermVector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SegmentWriteState.h"/#include "fnord-fts\/index\/SegmentWriteState.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SerialMergeScheduler.h"/#include "fnord-fts\/index\/SerialMergeScheduler.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SnapshotDeletionPolicy.h"/#include "fnord-fts\/index\/SnapshotDeletionPolicy.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SortedTermVectorMapper.h"/#include "fnord-fts\/index\/SortedTermVectorMapper.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StoredFieldsWriter.h"/#include "fnord-fts\/index\/StoredFieldsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StoredFieldsWriterPerThread.h"/#include "fnord-fts\/index\/StoredFieldsWriterPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Term.h"/#include "fnord-fts\/index\/Term.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermBuffer.h"/#include "fnord-fts\/index\/TermBuffer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermDocs.h"/#include "fnord-fts\/index\/TermDocs.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermEnum.h"/#include "fnord-fts\/index\/TermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermFreqVector.h"/#include "fnord-fts\/index\/TermFreqVector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermInfo.h"/#include "fnord-fts\/index\/TermInfo.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermInfosReader.h"/#include "fnord-fts\/index\/TermInfosReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermInfosWriter.h"/#include "fnord-fts\/index\/TermInfosWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermPositions.h"/#include "fnord-fts\/index\/TermPositions.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermPositionVector.h"/#include "fnord-fts\/index\/TermPositionVector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermsHash.h"/#include "fnord-fts\/index\/TermsHash.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermsHashConsumer.h"/#include "fnord-fts\/index\/TermsHashConsumer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermsHashConsumerPerField.h"/#include "fnord-fts\/index\/TermsHashConsumerPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermsHashConsumerPerThread.h"/#include "fnord-fts\/index\/TermsHashConsumerPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermsHashPerField.h"/#include "fnord-fts\/index\/TermsHashPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermsHashPerThread.h"/#include "fnord-fts\/index\/TermsHashPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorEntry.h"/#include "fnord-fts\/index\/TermVectorEntry.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorEntryFreqSortedComparator.h"/#include "fnord-fts\/index\/TermVectorEntryFreqSortedComparator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorMapper.h"/#include "fnord-fts\/index\/TermVectorMapper.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorOffsetInfo.h"/#include "fnord-fts\/index\/TermVectorOffsetInfo.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorsReader.h"/#include "fnord-fts\/index\/TermVectorsReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorsTermsWriter.h"/#include "fnord-fts\/index\/TermVectorsTermsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorsTermsWriterPerField.h"/#include "fnord-fts\/index\/TermVectorsTermsWriterPerField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorsTermsWriterPerThread.h"/#include "fnord-fts\/index\/TermVectorsTermsWriterPerThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermVectorsWriter.h"/#include "fnord-fts\/index\/TermVectorsWriter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FastCharStream.h"/#include "fnord-fts\/queryparser\/FastCharStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiFieldQueryParser.h"/#include "fnord-fts\/queryparser\/MultiFieldQueryParser.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryParseError.h"/#include "fnord-fts\/queryparser\/QueryParseError.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryParser.h"/#include "fnord-fts\/queryparser\/QueryParser.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryParserCharStream.h"/#include "fnord-fts\/queryparser\/QueryParserCharStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryParserConstants.h"/#include "fnord-fts\/queryparser\/QueryParserConstants.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryParserToken.h"/#include "fnord-fts\/queryparser\/QueryParserToken.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryParserTokenManager.h"/#include "fnord-fts\/queryparser\/QueryParserTokenManager.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BooleanClause.h"/#include "fnord-fts\/search\/BooleanClause.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BooleanQuery.h"/#include "fnord-fts\/search\/BooleanQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BooleanScorer.h"/#include "fnord-fts\/search\/BooleanScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BooleanScorer2.h"/#include "fnord-fts\/search\/BooleanScorer2.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CachingSpanFilter.h"/#include "fnord-fts\/search\/CachingSpanFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CachingWrapperFilter.h"/#include "fnord-fts\/search\/CachingWrapperFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Collector.h"/#include "fnord-fts\/search\/Collector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ComplexExplanation.h"/#include "fnord-fts\/search\/ComplexExplanation.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ConjunctionScorer.h"/#include "fnord-fts\/search\/ConjunctionScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ConstantScoreQuery.h"/#include "fnord-fts\/search\/ConstantScoreQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DefaultSimilarity.h"/#include "fnord-fts\/search\/DefaultSimilarity.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DisjunctionMaxQuery.h"/#include "fnord-fts\/search\/DisjunctionMaxQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DisjunctionMaxScorer.h"/#include "fnord-fts\/search\/DisjunctionMaxScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DisjunctionSumScorer.h"/#include "fnord-fts\/search\/DisjunctionSumScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocIdSet.h"/#include "fnord-fts\/search\/DocIdSet.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocIdSetIterator.h"/#include "fnord-fts\/search\/DocIdSetIterator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ExactPhraseScorer.h"/#include "fnord-fts\/search\/ExactPhraseScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Explanation.h"/#include "fnord-fts\/search\/Explanation.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldCache.h"/#include "fnord-fts\/search\/FieldCache.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldCacheImpl.h"/#include "fnord-fts\/search\/FieldCacheImpl.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldCacheRangeFilter.h"/#include "fnord-fts\/search\/FieldCacheRangeFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldCacheTermsFilter.h"/#include "fnord-fts\/search\/FieldCacheTermsFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldComparator.h"/#include "fnord-fts\/search\/FieldComparator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldComparatorSource.h"/#include "fnord-fts\/search\/FieldComparatorSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldDoc.h"/#include "fnord-fts\/search\/FieldDoc.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldDocSortedHitQueue.h"/#include "fnord-fts\/search\/FieldDocSortedHitQueue.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldValueHitQueue.h"/#include "fnord-fts\/search\/FieldValueHitQueue.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Filter.h"/#include "fnord-fts\/search\/Filter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FilteredDocIdSet.h"/#include "fnord-fts\/search\/FilteredDocIdSet.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FilteredDocIdSetIterator.h"/#include "fnord-fts\/search\/FilteredDocIdSetIterator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FilteredQuery.h"/#include "fnord-fts\/search\/FilteredQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FilteredTermEnum.h"/#include "fnord-fts\/search\/FilteredTermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FilterManager.h"/#include "fnord-fts\/search\/FilterManager.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ByteFieldSource.h"/#include "fnord-fts\/search\/function\/ByteFieldSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CustomScoreProvider.h"/#include "fnord-fts\/search\/function\/CustomScoreProvider.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CustomScoreQuery.h"/#include "fnord-fts\/search\/function\/CustomScoreQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocValues.h"/#include "fnord-fts\/search\/function\/DocValues.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DoubleFieldSource.h"/#include "fnord-fts\/search\/function\/DoubleFieldSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldCacheSource.h"/#include "fnord-fts\/search\/function\/FieldCacheSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldScoreQuery.h"/#include "fnord-fts\/search\/function\/FieldScoreQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IntFieldSource.h"/#include "fnord-fts\/search\/function\/IntFieldSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}OrdFieldSource.h"/#include "fnord-fts\/search\/function\/OrdFieldSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ReverseOrdFieldSource.h"/#include "fnord-fts\/search\/function\/ReverseOrdFieldSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ValueSource.h"/#include "fnord-fts\/search\/function\/ValueSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ValueSourceQuery.h"/#include "fnord-fts\/search\/function\/ValueSourceQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FuzzyQuery.h"/#include "fnord-fts\/search\/FuzzyQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FuzzyTermEnum.h"/#include "fnord-fts\/search\/FuzzyTermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}HitQueue.h"/#include "fnord-fts\/search\/HitQueue.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}HitQueueBase.h"/#include "fnord-fts\/search\/HitQueueBase.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexSearcher.h"/#include "fnord-fts\/search\/IndexSearcher.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MatchAllDocsQuery.h"/#include "fnord-fts\/search\/MatchAllDocsQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiPhraseQuery.h"/#include "fnord-fts\/search\/MultiPhraseQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiSearcher.h"/#include "fnord-fts\/search\/MultiSearcher.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiTermQuery.h"/#include "fnord-fts\/search\/MultiTermQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MultiTermQueryWrapperFilter.h"/#include "fnord-fts\/search\/MultiTermQueryWrapperFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NumericRangeFilter.h"/#include "fnord-fts\/search\/NumericRangeFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NumericRangeQuery.h"/#include "fnord-fts\/search\/NumericRangeQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ParallelMultiSearcher.h"/#include "fnord-fts\/search\/ParallelMultiSearcher.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}AveragePayloadFunction.h"/#include "fnord-fts\/search\/payloads\/AveragePayloadFunction.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MaxPayloadFunction.h"/#include "fnord-fts\/search\/payloads\/MaxPayloadFunction.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MinPayloadFunction.h"/#include "fnord-fts\/search\/payloads\/MinPayloadFunction.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PayloadFunction.h"/#include "fnord-fts\/search\/payloads\/PayloadFunction.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PayloadNearQuery.h"/#include "fnord-fts\/search\/payloads\/PayloadNearQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PayloadSpanUtil.h"/#include "fnord-fts\/search\/payloads\/PayloadSpanUtil.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PayloadTermQuery.h"/#include "fnord-fts\/search\/payloads\/PayloadTermQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PhrasePositions.h"/#include "fnord-fts\/search\/PhrasePositions.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PhraseQuery.h"/#include "fnord-fts\/search\/PhraseQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PhraseQueue.h"/#include "fnord-fts\/search\/PhraseQueue.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PhraseScorer.h"/#include "fnord-fts\/search\/PhraseScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PositiveScoresOnlyCollector.h"/#include "fnord-fts\/search\/PositiveScoresOnlyCollector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PrefixFilter.h"/#include "fnord-fts\/search\/PrefixFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PrefixQuery.h"/#include "fnord-fts\/search\/PrefixQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PrefixTermEnum.h"/#include "fnord-fts\/search\/PrefixTermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Query.h"/#include "fnord-fts\/search\/Query.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryTermVector.h"/#include "fnord-fts\/search\/QueryTermVector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}QueryWrapperFilter.h"/#include "fnord-fts\/search\/QueryWrapperFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ReqExclScorer.h"/#include "fnord-fts\/search\/ReqExclScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ReqOptSumScorer.h"/#include "fnord-fts\/search\/ReqOptSumScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ScoreCachingWrappingScorer.h"/#include "fnord-fts\/search\/ScoreCachingWrappingScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ScoreDoc.h"/#include "fnord-fts\/search\/ScoreDoc.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Scorer.h"/#include "fnord-fts\/search\/Scorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Searchable.h"/#include "fnord-fts\/search\/Searchable.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Searcher.h"/#include "fnord-fts\/search\/Searcher.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Similarity.h"/#include "fnord-fts\/search\/Similarity.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SimilarityDelegator.h"/#include "fnord-fts\/search\/SimilarityDelegator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SingleTermEnum.h"/#include "fnord-fts\/search\/SingleTermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SloppyPhraseScorer.h"/#include "fnord-fts\/search\/SloppyPhraseScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Sort.h"/#include "fnord-fts\/search\/Sort.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SortField.h"/#include "fnord-fts\/search\/SortField.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanFilter.h"/#include "fnord-fts\/search\/SpanFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanFilterResult.h"/#include "fnord-fts\/search\/SpanFilterResult.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanQueryFilter.h"/#include "fnord-fts\/search\/SpanQueryFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldMaskingSpanQuery.h"/#include "fnord-fts\/search\/spans\/FieldMaskingSpanQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NearSpansOrdered.h"/#include "fnord-fts\/search\/spans\/NearSpansOrdered.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NearSpansUnordered.h"/#include "fnord-fts\/search\/spans\/NearSpansUnordered.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanFirstQuery.h"/#include "fnord-fts\/search\/spans\/SpanFirstQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanNearQuery.h"/#include "fnord-fts\/search\/spans\/SpanNearQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanNotQuery.h"/#include "fnord-fts\/search\/spans\/SpanNotQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanOrQuery.h"/#include "fnord-fts\/search\/spans\/SpanOrQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanQuery.h"/#include "fnord-fts\/search\/spans\/SpanQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Spans.h"/#include "fnord-fts\/search\/spans\/Spans.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanScorer.h"/#include "fnord-fts\/search\/spans\/SpanScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanTermQuery.h"/#include "fnord-fts\/search\/spans\/SpanTermQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SpanWeight.h"/#include "fnord-fts\/search\/spans\/SpanWeight.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermSpans.h"/#include "fnord-fts\/search\/spans\/TermSpans.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermQuery.h"/#include "fnord-fts\/search\/TermQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermRangeFilter.h"/#include "fnord-fts\/search\/TermRangeFilter.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermRangeQuery.h"/#include "fnord-fts\/search\/TermRangeQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermRangeTermEnum.h"/#include "fnord-fts\/search\/TermRangeTermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TermScorer.h"/#include "fnord-fts\/search\/TermScorer.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TimeLimitingCollector.h"/#include "fnord-fts\/search\/TimeLimitingCollector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TopDocs.h"/#include "fnord-fts\/search\/TopDocs.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TopDocsCollector.h"/#include "fnord-fts\/search\/TopDocsCollector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TopFieldCollector.h"/#include "fnord-fts\/search\/TopFieldCollector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TopFieldDocs.h"/#include "fnord-fts\/search\/TopFieldDocs.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TopScoreDocCollector.h"/#include "fnord-fts\/search\/TopScoreDocCollector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Weight.h"/#include "fnord-fts\/search\/Weight.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}WildcardQuery.h"/#include "fnord-fts\/search\/WildcardQuery.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}WildcardTermEnum.h"/#include "fnord-fts\/search\/WildcardTermEnum.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BufferedIndexInput.h"/#include "fnord-fts\/store\/BufferedIndexInput.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BufferedIndexOutput.h"/#include "fnord-fts\/store\/BufferedIndexOutput.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ChecksumIndexInput.h"/#include "fnord-fts\/store\/ChecksumIndexInput.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ChecksumIndexOutput.h"/#include "fnord-fts\/store\/ChecksumIndexOutput.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Directory.h"/#include "fnord-fts\/store\/Directory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FileSwitchDirectory.h"/#include "fnord-fts\/store\/FileSwitchDirectory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FSDirectory.h"/#include "fnord-fts\/store\/FSDirectory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FSLockFactory.h"/#include "fnord-fts\/store\/FSLockFactory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexInput.h"/#include "fnord-fts\/store\/IndexInput.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}IndexOutput.h"/#include "fnord-fts\/store\/IndexOutput.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Lock.h"/#include "fnord-fts\/store\/Lock.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LockFactory.h"/#include "fnord-fts\/store\/LockFactory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MMapDirectory.h"/#include "fnord-fts\/store\/MMapDirectory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NativeFSLockFactory.h"/#include "fnord-fts\/store\/NativeFSLockFactory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NoLockFactory.h"/#include "fnord-fts\/store\/NoLockFactory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}RAMDirectory.h"/#include "fnord-fts\/store\/RAMDirectory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}RAMFile.h"/#include "fnord-fts\/store\/RAMFile.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}RAMInputStream.h"/#include "fnord-fts\/store\/RAMInputStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}RAMOutputStream.h"/#include "fnord-fts\/store\/RAMOutputStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SimpleFSDirectory.h"/#include "fnord-fts\/store\/SimpleFSDirectory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SimpleFSLockFactory.h"/#include "fnord-fts\/store\/SimpleFSLockFactory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SingleInstanceLockFactory.h"/#include "fnord-fts\/store\/SingleInstanceLockFactory.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Array.h"/#include "fnord-fts\/util\/Array.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Attribute.h"/#include "fnord-fts\/util\/Attribute.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}AttributeSource.h"/#include "fnord-fts\/util\/AttributeSource.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Base64.h"/#include "fnord-fts\/util\/Base64.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BitSet.h"/#include "fnord-fts\/util\/BitSet.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BitUtil.h"/#include "fnord-fts\/util\/BitUtil.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BitVector.h"/#include "fnord-fts\/util\/BitVector.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}BufferedReader.h"/#include "fnord-fts\/util\/BufferedReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CharFolder.h"/#include "fnord-fts\/util\/CharFolder.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CloseableThreadLocal.h"/#include "fnord-fts\/util\/CloseableThreadLocal.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Collator.h"/#include "fnord-fts\/util\/Collator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Collection.h"/#include "fnord-fts\/util\/Collection.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Constants.h"/#include "fnord-fts\/util\/Constants.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}CycleCheck.h"/#include "fnord-fts\/util\/CycleCheck.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}DocIdBitSet.h"/#include "fnord-fts\/util\/DocIdBitSet.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FieldCacheSanityChecker.h"/#include "fnord-fts\/util\/FieldCacheSanityChecker.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FileReader.h"/#include "fnord-fts\/util\/FileReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}FileUtils.h"/#include "fnord-fts\/util\/FileUtils.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}HashMap.h"/#include "fnord-fts\/util\/HashMap.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}HashSet.h"/#include "fnord-fts\/util\/HashSet.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InfoStream.h"/#include "fnord-fts\/util\/InfoStream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}InputStreamReader.h"/#include "fnord-fts\/util\/InputStreamReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LuceneAllocator.h"/#include "fnord-fts\/util\/LuceneAllocator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LuceneException.h"/#include "fnord-fts\/util\/LuceneException.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LuceneObject.h"/#include "fnord-fts\/util\/LuceneObject.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LuceneSignal.h"/#include "fnord-fts\/util\/LuceneSignal.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LuceneSync.h"/#include "fnord-fts\/util\/LuceneSync.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}LuceneThread.h"/#include "fnord-fts\/util\/LuceneThread.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Map.h"/#include "fnord-fts\/util\/Map.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MapOfSets.h"/#include "fnord-fts\/util\/MapOfSets.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}md5.h"/#include "fnord-fts\/util\/md5\/md5.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}MiscUtils.h"/#include "fnord-fts\/util\/MiscUtils.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}NumericUtils.h"/#include "fnord-fts\/util\/NumericUtils.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}OpenBitSet.h"/#include "fnord-fts\/util\/OpenBitSet.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}OpenBitSetDISI.h"/#include "fnord-fts\/util\/OpenBitSetDISI.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}OpenBitSetIterator.h"/#include "fnord-fts\/util\/OpenBitSetIterator.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}PriorityQueue.h"/#include "fnord-fts\/util\/PriorityQueue.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Random.h"/#include "fnord-fts\/util\/Random.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Reader.h"/#include "fnord-fts\/util\/Reader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ReaderUtil.h"/#include "fnord-fts\/util\/ReaderUtil.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ScorerDocQueue.h"/#include "fnord-fts\/util\/ScorerDocQueue.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Set.h"/#include "fnord-fts\/util\/Set.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SimpleLRUCache.h"/#include "fnord-fts\/util\/SimpleLRUCache.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SmallDouble.h"/#include "fnord-fts\/util\/SmallDouble.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}SortedVIntList.h"/#include "fnord-fts\/util\/SortedVIntList.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StringReader.h"/#include "fnord-fts\/util\/StringReader.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}StringUtils.h"/#include "fnord-fts\/util\/StringUtils.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}Synchronize.h"/#include "fnord-fts\/util\/Synchronize.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}TestPoint.h"/#include "fnord-fts\/util\/TestPoint.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}ThreadPool.h"/#include "fnord-fts\/util\/ThreadPool.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}gunichartables.h"/#include "fnord-fts\/util\/unicode\/gunichartables.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}guniprop.h"/#include "fnord-fts\/util\/unicode\/guniprop.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}UnicodeUtils.h"/#include "fnord-fts\/util\/UnicodeUtils.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}UTF8Stream.h"/#include "fnord-fts\/util\/UTF8Stream.h"/' $1
sed -ifnord -e 's/#include "\(.*\/\)\{0,1\}VariantUtils.h"/#include "fnord-fts\/util\/VariantUtils.h"/' $1
